import { useMemo } from 'react'
import { useDataStore } from '../../store'
import PageHeader from '../../components/common/PageHeader'
import Button from '../../components/common/Button'
import { Card, CardHeader, CardTitle, CardBody } from '../../components/common/Card'
import { useToast } from '../../hooks'

const TYPES = [
  { k:'TM',     l:'Trademark',    c:'#e85020' },
  { k:'PAT',    l:'Patent',       c:'#00aadd' },
  { k:'COPY',   l:'Copyright',    c:'#c89b30' },
  { k:'DESIGN', l:'Design',       c:'#7c3aed' },
  { k:'GI',     l:'GI',           c:'#1a7a4a' },
  { k:'HC',     l:'High Court',   c:'#c04010' },
  { k:'DC',     l:'District Ct.', c:'#c0392b' },
]

const STATUS_CLR = {
  'Pending':'#854d0e','Under Examination':'#2563eb','FER Issued':'#0090bb',
  'Hearing Fixed':'#e85020','Opposed':'#c0392b','Registered':'#065f46',
  'Renewal Due':'#c89b30','Filed':'#0090bb','Arguments':'#e85020',
  'Evidence':'#c89b30','Granted':'#065f46',
}

export default function Reports() {
  const { matters, clients, deadlines } = useDataStore()
  const toast = useToast()

  const total = matters.length || 1

  // Distribution
  const dist = TYPES.map(t => ({ ...t, n: matters.filter(m => m.type === t.k).length }))

  // Status breakdown
  const allStatuses = [...new Set(matters.map(m => m.status || m.stage).filter(Boolean))]
  const statusData  = allStatuses.map(s => ({ s, n: matters.filter(m => m.status === s || m.stage === s).length })).filter(x => x.n > 0)

  // Renewals
  const renewals = deadlines.filter(d => d.type?.toLowerCase().includes('renew')).sort((a,b) => new Date(a.date)-new Date(b.date))

  // Top clients
  const topClients = useMemo(() =>
    clients.map(c => ({ n: c.name, v: matters.filter(m => m.clientId === c.id).length }))
      .sort((a,b) => b.v - a.v).slice(0, 5),
    [clients, matters]
  )
  const maxC = Math.max(...topClients.map(c => c.v), 1)

  // Monthly filings 2026
  const months = ['Jan','Feb','Mar','Apr','May','Jun']
  const monthly = months.map((_, i) =>
    matters.filter(m => m.created && new Date(m.created).getMonth() === i && new Date(m.created).getFullYear() === 2026).length
  )
  const maxM = Math.max(...monthly, 1)

  const genDocket = () => {
    const w = window.open('', '_blank')
    const now = new Date()
    w.document.write(`<!DOCTYPE html><html><head><title>LawNetics Report</title>
    <style>body{font-family:Arial,sans-serif;max-width:780px;margin:40px auto;color:#1a2540}
    h1{border-bottom:3px solid #e85020;padding-bottom:.5rem}
    table{width:100%;border-collapse:collapse;font-size:.83rem}
    th{background:#0d2045;color:#fff;padding:.5rem;text-align:left}
    td{padding:.5rem;border-bottom:1px solid #e0e0e0}
    </style></head><body>
    <div style="display:flex;justify-content:space-between;margin-bottom:1rem">
      <div style="font-size:1.5rem;font-weight:900"><span style="color:#e85020">Law</span><span style="color:#0d2045">Netics</span></div>
      <div style="font-size:.72rem;color:#8a9bb5">CONFIDENTIAL · www.lawnetics.in</div>
    </div>
    <h1>Portfolio Report</h1>
    <p style="color:#8a9bb5;margin-bottom:1.5rem">${now.toLocaleDateString('en-IN',{weekday:'long',year:'numeric',month:'long',day:'numeric'})}</p>
    <h2>Matter Distribution</h2>
    <table><thead><tr><th>Type</th><th>Count</th><th>% of Portfolio</th></tr></thead>
    <tbody>${dist.map(d=>`<tr><td>${d.l}</td><td>${d.n}</td><td>${total?((d.n/total)*100).toFixed(1):'0'}%</td></tr>`).join('')}</tbody></table>
    <br/><h2>Top Clients</h2>
    <table><thead><tr><th>Client</th><th>Matters</th></tr></thead>
    <tbody>${topClients.map(c=>`<tr><td>${c.n}</td><td>${c.v}</td></tr>`).join('')}</tbody></table>
    <p style="font-size:.7rem;color:#aaa;margin-top:2rem;border-top:1px solid #e0e0e0;padding-top:1rem">
    Generated by LawNetics IP Docketing Portal · ${now.toLocaleString()}</p>
    </body></html>`)
    w.document.close()
    w.print()
  }

  return (
    <div className="animate-fadeUp">
      <PageHeader
        title="Reports & Analytics"
        subtitle="Portfolio insights, deadlines, workload analysis"
        actions={
          <>
            <Button variant="outline" size="sm" onClick={genDocket}>Export Docket PDF</Button>
            <Button size="sm" onClick={() => toast.info('Generating Excel report…')}>Export Excel</Button>
          </>
        }
      />

      {/* Row 1 – 3 charts */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-[1.1rem] mb-[1.1rem]">
        {/* Matter Distribution */}
        <Card>
          <CardHeader><CardTitle>Matter Distribution</CardTitle></CardHeader>
          <CardBody>
            {dist.map(t => (
              <div key={t.k} className="flex items-center gap-[0.62rem] mb-[0.48rem]">
                <div className="w-[68px] text-[0.68rem] text-text-2 shrink-0">{t.l}</div>
                <div className="flex-1 h-[5px] bg-bg-2 rounded-full overflow-hidden">
                  <div
                    className="h-full rounded-full transition-all duration-1000"
                    style={{ width: `${(t.n / total) * 100}%`, background: t.c }}
                  />
                </div>
                <div className="w-[17px] text-[0.76rem] font-bold text-navy">{t.n}</div>
              </div>
            ))}
          </CardBody>
        </Card>

        {/* Status Breakdown */}
        <Card>
          <CardHeader><CardTitle>Status Breakdown</CardTitle></CardHeader>
          <CardBody>
            {statusData.length > 0 ? statusData.map(({ s, n }) => (
              <div key={s} className="flex items-center justify-between px-[0.55rem] py-[0.35rem] bg-bg rounded-[5px] mb-[0.3rem]">
                <span className="text-[0.73rem] text-text-2">{s}</span>
                <span
                  className="text-[0.58rem] font-bold tracking-[0.06em] uppercase px-[0.5rem] py-[0.14rem] rounded"
                  style={{ background: (STATUS_CLR[s] || '#8a9bb5') + '22', color: STATUS_CLR[s] || '#8a9bb5' }}
                >
                  {n}
                </span>
              </div>
            )) : (
              <p className="text-[0.78rem] text-text-3">No matters yet.</p>
            )}
          </CardBody>
        </Card>

        {/* Renewals */}
        <Card>
          <CardHeader><CardTitle>Upcoming Renewals</CardTitle></CardHeader>
          <CardBody>
            {renewals.length > 0 ? renewals.map(d => (
              <div key={d.id} className="flex items-center gap-[0.55rem] px-[0.45rem] py-[0.45rem] bg-gold-light rounded-[6px] mb-[0.3rem]">
                <span className="text-[0.8rem]">🔄</span>
                <div className="flex-1 text-[0.72rem] text-text overflow-hidden whitespace-nowrap text-ellipsis">{d.matterName}</div>
                <span className="text-[0.66rem] font-bold text-gold shrink-0">{d.date}</span>
              </div>
            )) : (
              <p className="text-[0.76rem] text-text-3">No renewals tracked.</p>
            )}
          </CardBody>
        </Card>
      </div>

      {/* Row 2 – 2 charts */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-[1.1rem]">
        {/* Top Clients */}
        <Card>
          <CardHeader><CardTitle>Top Clients by Matters</CardTitle></CardHeader>
          <CardBody>
            {topClients.length > 0 ? topClients.map((c, i) => (
              <div key={i} className="flex items-center gap-[0.62rem] mb-[0.48rem]">
                <div className="w-[85px] text-[0.68rem] text-text-2 overflow-hidden whitespace-nowrap text-ellipsis shrink-0">
                  {c.n.split(' ')[0]}
                </div>
                <div className="flex-1 h-[5px] bg-bg-2 rounded-full overflow-hidden">
                  <div
                    className="h-full rounded-full bg-org transition-all duration-1000"
                    style={{ width: `${(c.v / maxC) * 100}%` }}
                  />
                </div>
                <div className="w-[17px] text-[0.76rem] font-bold text-navy">{c.v}</div>
              </div>
            )) : <p className="text-[0.76rem] text-text-3">No clients yet.</p>}
          </CardBody>
        </Card>

        {/* Monthly Filings Bar Chart */}
        <Card>
          <CardHeader><CardTitle>Monthly Filings (2026)</CardTitle></CardHeader>
          <CardBody>
            <div className="flex items-end gap-[5px] h-[90px]">
              {months.map((m, i) => (
                <div key={m} className="flex-1 flex flex-col items-center gap-[0.22rem]">
                  <div
                    className="bg-navy rounded-t-[3px] w-full min-h-[4px] transition-all duration-1000"
                    style={{ height: `${(monthly[i] / maxM) * 68 + 4}px` }}
                  />
                  <div className="text-[0.58rem] text-text-3">{m}</div>
                </div>
              ))}
            </div>

            {/* Summary Stats */}
            <div className="grid grid-cols-3 gap-2 mt-4 pt-4 border-t border-border">
              {[
                { l: 'Total',    v: matters.length },
                { l: 'Clients',  v: clients.length },
                { l: 'Deadlines',v: deadlines.length },
              ].map(s => (
                <div key={s.l} className="text-center">
                  <div className="font-serif text-[1.4rem] font-bold text-navy">{s.v}</div>
                  <div className="text-[0.62rem] text-text-3 uppercase tracking-wider">{s.l}</div>
                </div>
              ))}
            </div>
          </CardBody>
        </Card>
      </div>
    </div>
  )
}
