import { useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  MdPeople, MdWork, MdShield, MdCalendarMonth,
  MdFolder, MdGavel, MdAdd, MdDescription
} from 'react-icons/md'
import { useDataStore, useAuthStore, useUIStore } from '../../store'
import { Card, CardHeader, CardTitle, CardBody } from '../../components/common/Card'
import StatCard from '../../components/dashboard/StatCard'
import ActivityFeed from '../../components/dashboard/ActivityFeed'
import PortfolioGrid from '../../components/dashboard/PortfolioGrid'
import DeadlineItem from '../../components/common/DeadlineItem'
import Button from '../../components/common/Button'
import { TypeBadge, StatusBadge } from '../../components/common/Badge'
import { daysDiff, MONTHS_SHORT } from '../../utils/helpers'

export default function Dashboard() {
  const { user }                              = useAuthStore()
  const { openModal }                         = useUIStore()
  const { matters, clients, deadlines, documents, activity } = useDataStore()
  const navigate                              = useNavigate()

  const now = new Date()
  const todayFull = now.toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })

  // Urgent deadlines (≤7 days)
  const urgentCount = useMemo(() =>
    deadlines.filter(d => { const x = daysDiff(d.date); return x !== null && x >= 0 && x <= 7 }).length,
    [deadlines]
  )

  // Sorted deadlines for display
  const sortedDeadlines = useMemo(() =>
    [...deadlines].sort((a, b) => new Date(a.date) - new Date(b.date)).slice(0, 5),
    [deadlines]
  )

  // Recent matters
  const recentMatters = useMemo(() =>
    [...matters].sort((a, b) => new Date(b.created) - new Date(a.created)).slice(0, 5),
    [matters]
  )

  const generateDocket = () => {
    const dl = [...deadlines].sort((a, b) => new Date(a.date) - new Date(b.date)).slice(0, 12)
    const w = window.open('', '_blank')
    w.document.write(`<!DOCTYPE html><html><head><title>LawNetics Daily Docket</title>
    <style>body{font-family:Arial,sans-serif;max-width:780px;margin:40px auto;color:#1a2540}
    h1{border-bottom:3px solid #e85020;padding-bottom:.5rem}
    table{width:100%;border-collapse:collapse;font-size:.83rem}
    th{background:#0d2045;color:#fff;padding:.5rem .75rem;text-align:left}
    td{padding:.5rem .75rem;border-bottom:1px solid #e0e0e0}
    .ug{color:#c0392b;font-weight:bold}.wa{color:#c89b30}
    .head{display:flex;justify-content:space-between;margin-bottom:1rem}
    .logo{font-size:1.5rem;font-weight:900}.law{color:#e85020}.net{color:#0d2045}
    </style></head><body>
    <div class="head"><div class="logo"><span class="law">Law</span><span class="net">Netics</span></div>
    <div style="font-size:.72rem;color:#8a9bb5">CONFIDENTIAL · www.lawnetics.in</div></div>
    <h1>Daily Docket Sheet</h1>
    <p style="color:#8a9bb5;font-size:.82rem;margin-bottom:1.5rem">${todayFull}</p>
    <table><thead><tr><th>Date</th><th>Days</th><th>Type</th><th>Matter</th><th>Venue</th><th>Attorney</th></tr></thead>
    <tbody>${dl.map(d => {
      const diff = Math.ceil((new Date(d.date) - new Date()) / 86400000)
      const c = diff <= 3 ? 'ug' : diff <= 14 ? 'wa' : ''
      return `<tr><td class="${c}">${d.date}</td><td class="${c}">${diff < 0 ? 'OVERDUE' : diff === 0 ? 'TODAY' : diff + ' days'}</td><td>${d.type}</td><td>${d.matterName}</td><td>${d.venue || '—'}</td><td>${d.attorney}</td></tr>`
    }).join('')}</tbody></table>
    <p style="font-size:.7rem;color:#aaa;margin-top:2rem;border-top:1px solid #e0e0e0;padding-top:1rem">
    Generated by LawNetics IP Docketing Portal · ${new Date().toLocaleString()} · www.lawnetics.in</p>
    </body></html>`)
    w.document.close()
    w.print()
  }

  return (
    <div className="animate-fadeUp">
      {/* Page header */}
      <div className="flex items-start justify-between gap-4 mb-6 flex-wrap">
        <div>
          <h1 className="font-serif text-[1.65rem] font-bold text-navy leading-tight">
            Good Day, {user?.name?.split(' ')[0] || 'Advocate'}
          </h1>
          <p className="text-[0.79rem] text-text-3 mt-[0.18rem]">
            {todayFull} · <span className="text-red font-semibold">{urgentCount} urgent deadline{urgentCount !== 1 ? 's' : ''}</span>
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={generateDocket}>
            <MdDescription className="w-3.5 h-3.5" /> Daily Docket
          </Button>
          <Button size="sm" onClick={() => openModal('addMatter')}>
            <MdAdd className="w-3.5 h-3.5" /> New Matter
          </Button>
        </div>
      </div>

      {/* Stat Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-[0.9rem] mb-6">
        <StatCard value={clients.length}  label="Active Clients"   sub="Portfolio"       Icon={MdPeople}        color="org"   />
        <StatCard value={matters.length}  label="Total Matters"    sub="All types"       Icon={MdWork}          color="cyan"  />
        <StatCard value={matters.filter(m => m.type === 'TM').length} label="Trademark" sub="Active marks" Icon={MdShield} color="navy" />
        <StatCard value={urgentCount}     label="Urgent Deadlines" sub="Next 14 days"    Icon={MdCalendarMonth} color="gold"  />
        <StatCard value={documents.length}label="Documents"        sub="On Drive"        Icon={MdFolder}        color="green" />
        <StatCard value={matters.filter(m => ['HC','DC'].includes(m.type)).length} label="Court Cases" sub="HC + DC" Icon={MdGavel} color="red" />
      </div>

      {/* Dashboard Grid */}
      <div className="grid grid-cols-3 gap-[1.1rem]">
        {/* Upcoming Deadlines – span 2 */}
        <div className="col-span-3 lg:col-span-2">
          <Card>
            <CardHeader>
              <CardTitle>⚡ Upcoming Deadlines</CardTitle>
              <Button variant="ghost" size="sm" onClick={() => navigate('/docket-calendar')}>
                View All →
              </Button>
            </CardHeader>
            <CardBody>
              {sortedDeadlines.length > 0 ? (
                <div className="flex flex-col gap-[0.45rem]">
                  {sortedDeadlines.map(dl => (
                    <DeadlineItem key={dl.id} deadline={dl} />
                  ))}
                </div>
              ) : (
                <div className="text-center py-8 text-text-3 text-[0.82rem]">
                  No upcoming deadlines. Add events from the Docket Calendar.
                </div>
              )}
            </CardBody>
          </Card>
        </div>

        {/* Recent Activity */}
        <div className="col-span-3 lg:col-span-1">
          <Card className="h-full">
            <CardHeader><CardTitle>Recent Activity</CardTitle></CardHeader>
            <CardBody>
              <ActivityFeed items={activity.slice(0, 5)} />
            </CardBody>
          </Card>
        </div>

        {/* Portfolio Overview – span 2 */}
        <div className="col-span-3 lg:col-span-2">
          <Card>
            <CardHeader>
              <CardTitle>Matter Portfolio</CardTitle>
              <Button variant="ghost" size="sm" onClick={() => navigate('/reports')}>Reports →</Button>
            </CardHeader>
            <CardBody><PortfolioGrid /></CardBody>
          </Card>
        </div>

        {/* Recent Matters */}
        <div className="col-span-3 lg:col-span-1">
          <Card className="h-full">
            <CardHeader><CardTitle>Recent Matters</CardTitle></CardHeader>
            <CardBody noPadding>
              {recentMatters.map(m => (
                <div
                  key={m.id}
                  onClick={() => useUIStore.getState().openModal('matterDetail', m)}
                  className="flex items-center gap-[0.68rem] px-[0.9rem] py-[0.62rem] border-b border-border last:border-b-0 cursor-pointer hover:bg-bg transition-colors"
                >
                  <TypeBadge type={m.type} />
                  <div className="flex-1 min-w-0">
                    <div className="text-[0.79rem] font-semibold text-navy overflow-hidden whitespace-nowrap text-ellipsis">
                      {m.mark || m.caseTitle}
                    </div>
                    <div className="text-[0.67rem] text-text-3">{m.clientName}</div>
                  </div>
                  <StatusBadge status={m.status || m.stage} />
                </div>
              ))}
            </CardBody>
          </Card>
        </div>
      </div>
    </div>
  )
}
